name: Build and Deploy Documentation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Fetches all history for all tags and branches
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install
      working-directory: ./packages/docs

    - name: Build VitePress Documentation
      run: pnpm run build
      working-directory: ./packages/docs
